Feature/bug fix
oJieg/PrintingCalculator pull request #4
Opened 2022-08-11 13:33 UTC by oJieg

fix codeStyle

2022-08-11 14:06 UTC, Orygeunik requested changes
Есть что исправить
Есть общие повторящиющиеся ошибки, их написал 1/2 раза, дальше сам посмотри повторы по ним

2022-08-11 14:06 UTC, Orygeunik commented on ApplicationContext.cs
> +            //  Database.EnsureCreated();
Комментариям таким не место в репозитории

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
> +                result.Price = (int)Math.Round((double)Price / 10, 1) * 10; //округеление
Причем тут гель?
хм...

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                if (ActualConsumableId != history.ConsumablePrice.Id)
Можно упростить, сразу как `result.PaperResult.ActualConsumablePrice = ActualConsumableId != history.ConsumablePrice.Id`

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationPrise.cs
> +                // result.LaminationResult = new();
Аналогично - такие комменты не нужны

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperCostPrice.cs
> +        private readonly ApplicationContext _DB;
Я все надеюсь, что ты поправишь именование переменной контекста

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperCutPrise.cs
> +    public class PaperCutPrise : IConveyor
Price - цена
Prise - приз

У тебя тут чо должно быть?

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosCreasing.cs
> +            result.PosResult.ActualCreasingPrice = false;
Можно упростить

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosCreasing.cs
>              return true;
Тут и на 45 строке точно в обоих случаях return true?

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                return await _DB.Historys
Если история нужна только для чтения то забыт параметр AsNoTracing

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                     .FirstAsync();
CancelattionToken потерян

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +        public async Task<History?> GetFullIncludeHistoryAcync(int id)
Опечатка в постфиксе Async

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                     .FirstAsync();
Есть мето FirstOrDefault/FirstOrDefaultAsync - который вернет null, если ничего нет

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                if (input.LaminationName != "none")
магическая строковая константа!
СЖЕЧЬ!

2022-08-11 14:06 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                    .OrderByDescending(_ => _.Id)
не надо использовать _ - нижнее подчеркивание, используй букву/слово ассоццированное с целевой лямбдой

2022-08-11 14:06 UTC, Orygeunik commented on Models/Validstion.cs
> +    public class Validstion
Что это?
Как это должно называться/переводиться?!

2022-08-11 14:06 UTC, Orygeunik commented on Models/Validstion.cs
> +            return input != null &
Почему везде бинарные "И"?

2022-08-11 14:06 UTC, Orygeunik commented on Models/Validstion.cs
> +            return size != null & size > 0 & size > 0;
Почему бинарный "и" - почему два раза проверяешь size?

2022-08-11 14:06 UTC, Orygeunik commented on Models/Validstion.cs
> +            return await _BD.PaperCatalogs.AnyAsync(x => x.Name == namePaper);
AsNoTracking - забыт
не забывай его добавлять везде, где тебе потом не надо обновлять модель

2022-08-11 14:06 UTC, Orygeunik commented on Views/History/History.cshtml
>  @section Stail {
Бедный Сталин...

2022-08-11 14:06 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +<h1>История изменяя(Changelog)</h1>
Опечатка

2022-08-11 14:06 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +	<li>Добавлено отображение, на странице результатов, актуальность расчетов. (только верно ли общий расчет без детализации)</li>
Предложение не согласовано (то что в скобках вообще как отдельный кусок)

2022-08-11 14:06 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +	<li>Исправленный ошибки в текстах</li>
Перепиши эту строку, опечатки

2022-08-11 14:06 UTC, Orygeunik commented on Views/Shared/_Layout.cshtml
> -@*				<li class="li-margin"><a href="хз что">хз что</a></li>
Вытираем комменты за собой

2022-08-11 14:06 UTC, Orygeunik commented on appsettings.json
> +    //"Kestrel": {
Ну ты знаешь, что делать с комментами

2022-08-11 14:06 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +    alert(fullSize);
не стоит аллерт юзать

2022-08-11 14:06 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +    if (side == 'Width') {
Приведи к общему виду кавычки у строк.
Фиксированные вещи - вынеси в константу

2022-08-11 14:06 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +let Height = "297";
почему это строка? это же число

2022-08-11 14:29 UTC, oJieg commented on ApplicationContext.cs
> +            //  Database.EnsureCreated();
Хорошо, уберу всякое такое.

2022-08-11 14:31 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
> +                result.Price = (int)Math.Round((double)Price / 10, 1) * 10; //округеление
у меня нет объяснения)

2022-08-11 14:33 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                if (ActualConsumableId != history.ConsumablePrice.Id)
Пропустил, исправил

2022-08-11 14:34 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationPrise.cs
> +                // result.LaminationResult = new();
+

2022-08-11 14:49 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCostPrice.cs
> +        private readonly ApplicationContext _DB;
Переименовал

2022-08-11 14:53 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCutPrise.cs
> +    public class PaperCutPrise : IConveyor
Поправил, там много где такого еще нашел(

2022-08-11 14:54 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosCreasing.cs
> +            result.PosResult.ActualCreasingPrice = false;
упростил

2022-08-11 14:55 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosCreasing.cs
>              return true;
да, тут тру или фелс обозначает только получилось ли нормально посчитать.

2022-08-12 14:56 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +        public async Task<History?> GetFullIncludeHistoryAcync(int id)
поправил

2022-08-12 14:57 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                if (input.LaminationName != "none")
ладно ладно)

2022-08-12 14:58 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                    .OrderByDescending(_ => _.Id)
а x это считается?

2022-08-12 14:59 UTC, oJieg commented on Models/Validstion.cs
> +    public class Validstion
Валидация видимо) поправил

2022-08-12 15:01 UTC, oJieg commented on Models/Validstion.cs
> +            return input != null &
да поправил на &&, логично что не нужно проверять после первого косяка

2022-08-12 15:03 UTC, oJieg commented on Models/Validstion.cs
> +            return size != null & size > 0 & size > 0;
да поправил на &&, и второй раз там ошибка, поправил.

2022-08-12 15:04 UTC, oJieg commented on Models/Validstion.cs
> +            return await _BD.PaperCatalogs.AnyAsync(x => x.Name == namePaper);
Исправил

2022-08-12 15:06 UTC, oJieg commented on Views/History/History.cshtml
>  @section Stail {
style, поправил

2022-08-12 15:06 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +<h1>История изменяя(Changelog)</h1>
опечатка

2022-08-12 21:09 UTC, Orygeunik requested changes
Есть еще замечания

2022-08-12 21:09 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
>          public ConsumablePrice(Consumable consumable, ApplicationContext DB)
Ну почти, теперь еще имя параметра приведи к одному виду, и будет торт)

2022-08-12 21:09 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefault().Id;
1. не асинк
2. если у тебя сработает ветка OrDefault, ты получишь null, и от него не сможешь взять id

2022-08-12 21:09 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                _logger.LogError(ex, "Не вышло получить список истории,");
Появилась запятая. Типо интрига?

2022-08-12 21:09 UTC, Orygeunik commented on Models/Validation.cs
>              return input != null &
Тут остался бинарный &

2022-08-12 21:09 UTC, Orygeunik commented on Models/Validation.cs
> +                .AnyAsync(x => x.Name == namePaper);
CancallationToken потерян 
не любишь их ты :(

2022-08-12 21:09 UTC, Orygeunik commented on Models/Validation.cs
> +            return number > 0 && number < int.MaxValue;
Не хочу тебя расстраивать, но ты в int не сможешь положить больше чем int.MaxValue, вот вообще никак

2022-08-12 21:09 UTC, Orygeunik commented on Views/calculator/Calculator.cshtml
>  <script src="/ActiveSize.js"></script>
У тебя в блоке "СТИЛИ" лежит JS скрипт. Кто-то врет

2022-08-18 09:37 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                return await _DB.Historys
ок

2022-08-18 09:42 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +	<li>Добавлено отображение, на странице результатов, актуальность расчетов. (только верно ли общий расчет без детализации)</li>
ох уж эти языки

2022-08-18 09:43 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +	<li>Исправленный ошибки в текстах</li>
исправил

2022-08-18 09:54 UTC, oJieg commented on Views/Shared/_Layout.cshtml
> -@*				<li class="li-margin"><a href="хз что">хз что</a></li>
Убрал

2022-08-18 09:55 UTC, oJieg commented on appsettings.json
> +    //"Kestrel": {
Этот конкретно комментарии нужен, он разкоментируется когда на сервер загружаю

2022-08-18 10:17 UTC, oJieg commented on wwwroot/ActiveSize.js
> +    if (side == 'Width') {
ok

2022-08-18 10:18 UTC, oJieg commented on wwwroot/ActiveSize.js
> +let Height = "297";
я ее дальше как строку использовал просто. Исправил

2022-08-18 10:19 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
>          public ConsumablePrice(Consumable consumable, ApplicationContext DB)
Ты просто рано проверять начал)

2022-08-18 10:20 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefault().Id;
Да, только переработал конвейер что бы асинк методы можно было сделать.

2022-08-18 10:21 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                _logger.LogError(ex, "Не вышло получить список истории,");
Убрал интригу)

2022-08-18 10:21 UTC, oJieg commented on Models/Validation.cs
>              return input != null &
точно)

2022-08-18 10:24 UTC, oJieg commented on Models/Validation.cs
> +            return number > 0 && number < int.MaxValue;
Даже если клиент пришлет такое серверу?

2022-08-18 10:26 UTC, oJieg commented on Views/calculator/Calculator.cshtml
>  <script src="/ActiveSize.js"></script>
Исправил

2022-08-18 11:37 UTC, oJieg commented on wwwroot/ActiveSize.js
> +    if (side == 'Width') {
Но кавычки в js вроде так принято сделать( и студия сама меняет на такой стиль.

2022-08-19 11:21 UTC, oJieg commented on Models/Validation.cs
> +                .AnyAsync(x => x.Name == namePaper);
Ну как то я это сделал, не уверен что верно.

2022-08-19 11:22 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                     .FirstAsync();
ок

2022-08-19 11:22 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                     .FirstAsync();
вроде добавил.

2022-08-19 17:48 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
>          public ConsumablePrice(Consumable consumable, ApplicationContext DB)
а теперь уже можно или еще нет?

2022-08-19 17:48 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefaultAsync();
Токена не вижу туть

2022-08-19 17:48 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefaultAsync();
Все Async - штуки принимают токен

2022-08-19 17:49 UTC, Orygeunik commented on Models/Validation.cs
> +            return number > 0 && number < int.MaxValue;
Да, если клиент пришлет, что-то, что непоместиться в инт - то оно не дойдет до этого кода, вообще

2022-08-19 17:57 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                    .OrderByDescending(_ => _.Id)
в целом пойдет (но не увлекайся таким, особенно если будет несколько лямбд!)

2022-08-19 17:59 UTC, Orygeunik commented on appsettings.json
> +    //"Kestrel": {
Это НЕ правильное поведение. Так делать нельзя
Для таких вещей есть `appsetting.PRODUCTION.json`

2022-08-19 18:00 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +    if (side == 'Width') {
у теья там были кавычки разных типов

2022-08-19 18:11 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +    if (side == 'Width') {
![image](https://user-images.githubusercontent.com/6960655/185681261-25d39de3-bfaf-43f3-806d-66e8b7f882a6.png)

2022-08-20 14:00 UTC, oJieg commented on wwwroot/ActiveSize.js
> +    alert(fullSize);
Удалил

2022-08-20 14:00 UTC, oJieg commented on wwwroot/ActiveSize.js
> +    if (side == 'Width') {
понял, поправил

2022-08-20 14:00 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
>          public ConsumablePrice(Consumable consumable, ApplicationContext DB)
вроде да)

2022-08-20 14:01 UTC, oJieg commented on Models/Validation.cs
> +            return number > 0 && number < int.MaxValue;
лаадно, убрал тогда.

2022-08-20 15:18 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefaultAsync();
теперь принимают

2022-08-20 21:08 UTC, Orygeunik requested changes
Есть ряд замечаний

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +                int CostPrice = (int)((history.LaminationPrices.Price + _lamination1.Job) * result.PaperResult.Sheets);
Именование локальной пельменной с маленькой буквы

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        }
Пустой строки не хватает

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        public LamonationCostPriсe(Settings.Lamination lamination, ApplicationContext applicationContext, CancellationToken cancellationToken)
Пустой строки не хватает

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +            _cancellationToken = cancellationToken;
Эм... почему он у тебя в конструкторе, а не в методе?

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationInfo.cs
>                  catch
А скажи, зачем тебе тут try/catch ? Вообще где ты тут ошибку ожидаешь получить?

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
>                  catch
Аналогично. Где у тебя тут должна и какая ошибка произойти? Зачем тут try/catch?

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +        private const int AdjustmentCutOne = 30; //количество листов в одной привертке при резке
А что насчет имени
CountOfPapersInOneAdjustmentCut

Тогда и комментария не надо

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
>              result.PaperResult.Price = (int)(result.PaperResult.CostPrise + (result.PaperResult.CostPrise * (float)result.PaperResult.MarkupPaper / (float)100)) + result.PaperResult.CutPrics; //време
Подозрительный коммент

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosCreasing.cs
>              //мб валидацию добавить?
Если на до что-то добавить потом, но сейчас нет ресурсов, оставляют в коде TODO
`//TODO: сделать валидацию`
Студия умеет подхватывать такие туду - и давать тебе список их

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosDrilling.cs
>              result.PosResult.ActualDrillingPrice = true;
Кажется тут, и на строках 38/40 - ошибка в логике. Проверь, почему у тебя 2 ветки кода, делают одно и то же.

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
>              result.PosResult.RoundingPrice = (int)Price;
Строка 37 - дублриует эту, только нам обращение как к nullable int, а тут как каст к инту. Явно какая-то ошибка

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculator.cs
> +            _cancellationToken = cancellationToken;
Не надо сохранять токен как член класса. Токен отмены должен всегда быть "свежим", т.е. прокидываться как параметр, а не как член класса

Т.е. это должен быть параметр метода TryRun

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +
Лишняя строка

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                    .Include(x => x.Prices)
Почитай про ThenInclude, вполне вероятно, тебе не надо делать второй метод для наполнения

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                    history.Input.Lamination = new Lamination();
А зачем сначала делать класс дефолтный, а потом вместо него присваивать совсем другой?

2022-08-20 21:08 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                return null;
Тут и на 123 строке, у тебя разные возвращаемые результаты. Ты точно на вызывающей стороне правильно обработаешь null?

2022-08-20 21:08 UTC, Orygeunik commented on Models/Validation.cs
> +            if (nameLamination != "none")
Вынеси в константу. Если еще где-то есть, то константу на уровень приложения

2022-08-20 21:08 UTC, Orygeunik commented on Views/CalculatorResult/CalculatorResult.cshtml
>  	function copu() {
А что такое copu? Это сопу?

2022-08-20 21:08 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +<h1>История изменяя(Changelog)</h1>
Давай помогу, тут должно быть слово
`изменений`

2022-08-20 21:08 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +	<li>На странице с результат добавлено отображение актуальности цены. (только верно ли общий расчет без детализации)</li>
Текст в скобках, лично я не очень понял :(

2022-08-20 21:08 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +	<li>Исправленны ошибки в текстах</li>
Одна `н`, если что :)

2022-08-20 21:08 UTC, Orygeunik commented on controllers/CalculatorController.cs
> +                    PaperAndHistoryInput.Input = (await _applicationContext.Historys.Where(s => s.Id == HistoryId).Include(x => x.Input).FirstAsync(cancellationToken)).Input;
Лучше разбей это на строки, каждое действие /where/include - на новой строке

2022-08-20 21:08 UTC, Orygeunik commented on controllers/CalculatorController.cs
> +                    return BadRequest();
Не стоит возвращать 401 на это

2022-08-20 21:08 UTC, Orygeunik commented on controllers/CalculatorResultController.cs
> +            _validstion = validstion;
Явно это какая-то помесь
фантастишь и валидация - валидастишь... хм...

2022-08-20 21:08 UTC, Orygeunik commented on controllers/CalculatorResultController.cs
> +            var answer = await conveyor.TryStartCalculation(history, result, cancellationToken); //как то странно выглядит но все же
А что странно?
А почему var?

2022-08-20 21:08 UTC, Orygeunik commented on controllers/CalculatorResultController.cs
> +                _logger.LogError("не удался расчет на конвеере");
В слове конвейер - есть буква Й

2022-08-20 21:08 UTC, Orygeunik commented on controllers/HistoryController.cs
> +        public async Task<IActionResult> Index(int page, CancellationToken cancellationToken, int countPage = 10)
Токен лучше ставить в конец, как последний параметр

2022-08-20 21:08 UTC, Orygeunik commented on controllers/ValuesProcessingController.cs
> +           // TestAddConsumablePrice();
Мало тут у тебя комментов конечно, всего 10 строк

2022-08-20 21:08 UTC, Orygeunik commented on controllers/ValuesProcessingController.cs
>              // ViewData["Massage"] = DB.Markups.First().Id.ToString();
Точно оно должно быть закомментированно?
И что за Массаж?

2022-08-20 21:08 UTC, Orygeunik commented on controllers/ValuesProcessingController.cs
>              return View("PageOtvet", catalog);
Ответ - это answer, например

2022-08-20 21:08 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +const ClassFastHover = "FastHover";
в JS все именования начинаются с маленькой буквы, т.е. должно быть `classFastHover`

2022-08-20 21:08 UTC, Orygeunik commented on appsettings.json
> +    //"Kestrel": {
Все еще активно

2022-08-21 12:10 UTC, oJieg commented on appsettings.json
> +    //"Kestrel": {
ок

2022-08-21 12:11 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +                int CostPrice = (int)((history.LaminationPrices.Price + _lamination1.Job) * result.PaperResult.Sheets);
+

2022-08-21 12:11 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        }
+

2022-08-21 12:12 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        public LamonationCostPriсe(Settings.Lamination lamination, ApplicationContext applicationContext, CancellationToken cancellationToken)
+

2022-08-21 12:14 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +            _cancellationToken = cancellationToken;
потому что иначе придется всем классам передавать этот токен, и тем что не нужно. Логичное через конструктор тогда уже получить что нужно именно этому классу.

2022-08-21 12:14 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationInfo.cs
>                  catch
логично, убрал

2022-08-21 12:17 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
>                  catch
убрал

2022-08-21 12:19 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +        private const int AdjustmentCutOne = 30; //количество листов в одной привертке при резке
но я пожалуй все равно оставлю комментарий, боюсь в последствии не пойму что значит  "Количество листов в одном регулировочном разрезе"

2022-08-21 12:20 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
>              result.PaperResult.Price = (int)(result.PaperResult.CostPrise + (result.PaperResult.CostPrise * (float)result.PaperResult.MarkupPaper / (float)100)) + result.PaperResult.CutPrics; //време
да, временное стало постоянным(

2022-08-21 12:24 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosCreasing.cs
>              //мб валидацию добавить?
пожалуй вообще не актуальный комментарий. Но про TODO не знал

2022-08-21 12:26 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosDrilling.cs
>              result.PosResult.ActualDrillingPrice = true;
да, пожалуй, не заметил

2022-08-21 12:29 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
>              result.PosResult.RoundingPrice = (int)Price;
вынес эту строку выше, хз зачем я ее продублировал

2022-08-21 12:30 UTC, oJieg commented on Models/Calculating/ConveyorCalculator.cs
> +            _cancellationToken = cancellationToken;
ладно переделаю интерфейс

2022-08-21 12:34 UTC, oJieg commented on Models/Calculating/ConveyorCalculator.cs
> +            _cancellationToken = cancellationToken;
и тогда уже везде проверку на отмену сделаю, даже в синхронных методах, а то жалко просто так этот токен передавать.

2022-08-21 12:47 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +
+

2022-08-21 13:23 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                    history.Input.Lamination = new Lamination();
хз, в какой то момент без этого не работало..

2022-08-21 13:24 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                return null;
хм, да верно, ошибка.

2022-08-21 13:52 UTC, oJieg commented on Views/CalculatorResult/CalculatorResult.cshtml
>  	function copu() {
CopyСlipboard переименовал

2022-08-21 13:53 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +<h1>История изменяя(Changelog)</h1>
спасибо(

2022-08-21 13:54 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +	<li>На странице с результат добавлено отображение актуальности цены. (только верно ли общий расчет без детализации)</li>
поправил, мб будет понятнее

2022-08-21 13:54 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +	<li>Исправленны ошибки в текстах</li>
+

2022-08-21 13:56 UTC, oJieg commented on controllers/CalculatorController.cs
> +                    PaperAndHistoryInput.Input = (await _applicationContext.Historys.Where(s => s.Id == HistoryId).Include(x => x.Input).FirstAsync(cancellationToken)).Input;
+

2022-08-21 14:24 UTC, oJieg commented on controllers/CalculatorController.cs
> +                    return BadRequest();
ок EmptyResult отправлю

2022-08-21 14:25 UTC, oJieg commented on controllers/CalculatorResultController.cs
> +            _validstion = validstion;
+

2022-08-21 14:29 UTC, oJieg commented on controllers/CalculatorResultController.cs
> +            var answer = await conveyor.TryStartCalculation(history, result, cancellationToken); //как то странно выглядит но все же
var что бы не писать длинную строку - (History, Result, bool) )
А странно с кортежем этим. Приходится через переменную answer все делать.

2022-08-21 14:29 UTC, oJieg commented on controllers/CalculatorResultController.cs
> +                _logger.LogError("не удался расчет на конвеере");
+

2022-08-21 14:31 UTC, oJieg commented on controllers/HistoryController.cs
> +        public async Task<IActionResult> Index(int page, CancellationToken cancellationToken, int countPage = 10)
да, но нельзя поставить необязательный параметр в середину же. По этому countPage в конце должна быть

2022-08-21 14:55 UTC, oJieg commented on controllers/ValuesProcessingController.cs
> +           // TestAddConsumablePrice();
Это тестовый контроллер, можно я его в таком состоянии оставлю? ) Как только можно будет по человечески взаимодействовать с вот этими настройками этот контроллер удалится вовсе.

2022-08-22 14:23 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                    .Include(x => x.Prices)
Не плохо, спасибо за наводку

2022-08-22 15:05 UTC, oJieg commented on Models/Validation.cs
> +            if (nameLamination != "none")
Готово.

2022-08-22 15:27 UTC, oJieg commented on controllers/ValuesProcessingController.cs
>              // ViewData["Massage"] = DB.Markups.First().Id.ToString();
+

2022-08-22 15:27 UTC, oJieg commented on controllers/ValuesProcessingController.cs
>              return View("PageOtvet", catalog);
+

2022-08-22 15:34 UTC, oJieg commented on wwwroot/ActiveSize.js
> +const ClassFastHover = "FastHover";
Поправил

2022-08-24 01:39 UTC, Orygeunik requested changes
Уже лучше, но есть что пропустил

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
>          private bool ActualMarkup(History history, int markup)
А зачем этот метод, если он вообще в 1 строку превращается (history.LaminationMarkup == markup)

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
>              catch
А какую ты тут ошибку вообще ожидаешь? Почему тут должно быть исключение?

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperCostPrice.cs
> +                if (PriceId == ActualPriceId[^1].Id)
Можно сразу return PriceId == ActualPriceId[^1].Id

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +            catch
А тут почему ошибка может быть?

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +        private bool ActualCutPrice(int? historyPrice, int cutPrice)
Метод можно в 1 строку свернуть и убрать его

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperInfo.cs
>              catch
А тут где/почему ошибка должна быть?

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperMarkup.cs
>          private bool ActualMarkup(History history, int markup)
То же самое, в 1 строку и выкинуть метод

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
> +            catch
Какую ошибку и почему ждем?

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
>              int? Price = history.RoundingPrice;
Именование лоальных переменных хромает

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculator.cs
> +                var answer = await conveyor.TryConveyorStartAsync(history, result, cancellationToken);
Пока тебе низя использовать вары :)

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                        .First();
FirstAsync

2022-08-24 01:39 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                    .First();
FirstAsync

2022-08-24 01:39 UTC, Orygeunik commented on Models/Validation.cs
> +            return size != null && size > 0 && size < 2000;
число 2000 кажется менялось, до того было что-то другое
рекомендую вынести в конфиг, такое

2022-08-24 01:39 UTC, Orygeunik commented on Models/Validation.cs
> +            return countPos > 0 && countPos < 50; //не больше 50 биговок и дырок))
Пустая строка + число 50 закинь в конфиг

2022-08-24 01:39 UTC, Orygeunik commented on Views/CalculatorResult/CalculatorResult.cshtml
> +	function CopyСlipboard() {
В JS функции именуются начиная с маленькой буквы, а потом каждое слово с большой
У тебя примерн на 28 строке 
![image](https://user-images.githubusercontent.com/6960655/186297637-e0cfccee-2fd0-43e7-9af6-ef57e0685cbc.png)

2022-08-24 01:39 UTC, Orygeunik commented on Views/Homes/Chengelog.cshtml
> +	<li>На странице с результат добавлено отображение актуальности цены. (только верно ли общая цена без детализации)</li>
`верна ли` - цена женский род

2022-08-24 01:39 UTC, Orygeunik commented on appsetting.PRODUCTION.json
> +{
Воу... капсом то не надо было писать
`Production` - так уж лучше

2022-08-24 01:39 UTC, Orygeunik commented on appsetting.PRODUCTION.json
> +  "Logging": {
Дублировать теже самые настройки не надо
Конфигурация работает так, что если никто не перекрыл опцию - берется из родителя

2022-08-24 01:39 UTC, Orygeunik commented on appsetting.PRODUCTION.json
> +      "Adjustment": 50, //���� �������� ���������
Коооооооооооооооодировка!
Только UTF-8

2022-08-24 01:39 UTC, Orygeunik commented on controllers/CalculatorController.cs
> +                    return BadRequest();
BadRequest - это 400 код
Это не пустой

2022-08-24 01:39 UTC, Orygeunik commented on controllers/CalculatorResultController.cs
> +            _validstion = validstion;
Намеренно ен стал переименовывать?

2022-08-24 01:39 UTC, Orygeunik commented on controllers/ValuesProcessingController.cs
> +    //DOTO: Веременная заглушка. Удалить в след патче, после добавления функционала изменения каталога бумаги и цен расходников.
TODO, а не наоборот.... ох...

2022-08-24 01:39 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +const �lassFastHover = "FastHover";
а что это за буква? 
![изображение_2022-08-24_043912742](https://user-images.githubusercontent.com/6960655/186298607-af1bad62-6b57-4587-8b91-ddd5b0654d20.png)

2022-08-24 01:40 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +            _cancellationToken = cancellationToken;
Нет, этот параметр передается строго каждому классу, каждому методу, он не кладется в приватный член класса. Всегда только свежее значение

2022-08-24 01:43 UTC, Orygeunik commented on controllers/CalculatorResultController.cs
> +            var answer = await conveyor.TryStartCalculation(history, result, cancellationToken); //как то странно выглядит но все же
Как раз таки если будешь использовать не var у тебя будет возможность сделать деконструирование кортежа.
Почитай про это

2022-08-24 07:35 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
>          private bool ActualMarkup(History history, int markup)
Хороший вопрос) убрал

2022-08-24 07:37 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
>              catch
Переполнение int. Теоретически в запросе можно положить очень большую цифру. При том не только в запросе, может так же и другие переменные в настройках быть очень не корректными из за чего все это сломается.

2022-08-24 07:38 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCostPrice.cs
> +                if (PriceId == ActualPriceId[^1].Id)
Логично

2022-08-24 07:39 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +            catch
Все так же переполнение int

2022-08-24 07:40 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +        private bool ActualCutPrice(int? historyPrice, int cutPrice)
+

2022-08-24 07:40 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperInfo.cs
>              catch
Да тут лишнее

2022-08-24 07:41 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperMarkup.cs
>          private bool ActualMarkup(History history, int markup)
Ок

2022-08-24 07:42 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
> +            catch
Все так же переполнение int

2022-08-24 07:42 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
>              int? Price = history.RoundingPrice;
Поправил

2022-08-24 07:43 UTC, oJieg commented on Models/Calculating/ConveyorCalculator.cs
> +                var answer = await conveyor.TryConveyorStartAsync(history, result, cancellationToken);
Ок, развернул)

2022-08-24 07:46 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                        .First();
Но это же не обращение к базе. Он и не даёт асинк версию использовать

2022-08-24 07:46 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                    .First();
Но это же обращение не к базе. Он тут и не даёт использовать асинк версию

2022-08-24 08:03 UTC, oJieg commented on Models/Validation.cs
> +            return size != null && size > 0 && size < 2000;
Пожалуй. Вынес

2022-08-24 08:04 UTC, oJieg commented on Models/Validation.cs
> +            return countPos > 0 && countPos < 50; //не больше 50 биговок и дырок))
Поправил

2022-08-24 08:05 UTC, oJieg commented on Views/CalculatorResult/CalculatorResult.cshtml
> +	function CopyСlipboard() {
Поправил

2022-08-24 08:06 UTC, oJieg commented on appsetting.PRODUCTION.json
> +{
Ок)

2022-08-24 08:07 UTC, oJieg commented on Views/Homes/Chengelog.cshtml
> +	<li>На странице с результат добавлено отображение актуальности цены. (только верно ли общая цена без детализации)</li>
Поправил

2022-08-24 08:07 UTC, oJieg commented on appsetting.PRODUCTION.json
> +  "Logging": {
Каеф, удобно

2022-08-24 14:56 UTC, oJieg commented on controllers/ValuesProcessingController.cs
> +    //DOTO: Веременная заглушка. Удалить в след патче, после добавления функционала изменения каталога бумаги и цен расходников.
lol))

2022-08-24 14:57 UTC, oJieg commented on wwwroot/ActiveSize.js
> +const �lassFastHover = "FastHover";
Видимо русская C)) Странно что это вообще работало.

2022-08-24 15:01 UTC, oJieg commented on appsetting.PRODUCTION.json
> +      "Adjustment": 50, //���� �������� ���������
Вроде он и стоит. Странно

2022-08-26 00:09 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
>              catch
Это.... очень странный кейс и не очевидный
Укажи явно в конструкте catch что ты именно ошибку переполнения ожидаешь, тогда хоть как-то код станет яснее

2022-08-26 00:10 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
>              int? Price = history.RoundingPrice;
В остальных местах код посмотри, я там пошел смотреть и уже нашел
В студии так же проверь вкладку инфомрации, там не должно быть замечаний

2022-08-26 00:13 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculator.cs
> +                (History, Result, bool) answer = await conveyor.TryConveyorStartAsync(history, result, cancellationToken);
А теперь поставь к ним имена, как к переменным :)

2022-08-26 00:14 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                        .First();
Можно тогда было просто [0] использовать :)

2022-08-26 00:15 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculator.cs
> +                (History, Result, bool) answer = await conveyor.TryConveyorStartAsync(history, result, cancellationToken);
Обращаю внимание на этот коммент
https://github.com/oJieg/PrintingCalculator/pull/4#discussion_r953246446

2022-08-26 00:17 UTC, Orygeunik commented on Views/CalculatorResult/CalculatorResult.cshtml
> +@if (!Model.TryTrice)
TryTrice - это типо "попробуй потрести"?

2022-08-26 00:20 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +    document.getElementById("Height").value = HeightPaper;
Возможно, можно сделать в const переменную и 1 раз искать элемент

2022-08-26 00:21 UTC, Orygeunik commented on wwwroot/ActiveSize.js
> +function editSize(HeightPaper, WidthPaper) {
Почему с большой буквы параметры? На 7 строке норм же

2022-08-31 09:12 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
>              catch
ок поправил, оказывается преобразование в инт через (int) и не ловит исключение, просто на второй круг выходит значение, получаем минус просто)))

2022-08-31 09:16 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                        .First();
Так как то уже привычнее и единообразнее что ли. Да и точно сортировка правильная будет.

2022-08-31 09:17 UTC, oJieg commented on Models/Calculating/ConveyorCalculator.cs
> +                (History, Result, bool) answer = await conveyor.TryConveyorStartAsync(history, result, cancellationToken);
понял, чет сразу не сообразил так сделать.

2022-08-31 09:22 UTC, oJieg commented on Views/CalculatorResult/CalculatorResult.cshtml
> +@if (!Model.TryTrice)
Опячаточка)

2022-08-31 09:26 UTC, oJieg commented on wwwroot/ActiveSize.js
> +    document.getElementById("Height").value = HeightPaper;
да, так по красивше выходит.

2022-08-31 09:26 UTC, oJieg commented on wwwroot/ActiveSize.js
> +function editSize(HeightPaper, WidthPaper) {
поправил

2022-09-02 18:58 UTC, Orygeunik requested changes

2022-09-02 18:58 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            if (priceId == actualPriceId[^1].Id)
Можно схлопнуть в 1 return

2022-09-02 18:58 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        private readonly Settings.Lamination _lamination1;
Почему единичка?

2022-09-02 18:58 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
> +                int? price = Convert.ToInt32(result.PaperResult.CostPrise + (result.PaperResult.CostPrise * (float)result.PaperResult.MarkupPaper / (float)100)) + result.PaperResult.CutPrics;
Длинная строка, старайся не делать их такими

2022-09-02 18:58 UTC, Orygeunik commented on Models/Calculating/GeneratorHistory.cs
> +                    .AsNoTracking()
Ты можешь добавлять по условию нужные элементы, не делая дубль метода, т.е. примерно так
```
var q = context.Table.Where(x => x.size == 1);

q = q.Where(x => x.count > 0)

if(!needTrack)
q = q.AsNoTraking()
```

И в конце уже используешь "материализацию"
`result = q.First()`

2022-09-02 18:58 UTC, Orygeunik commented on Models/Validation.cs
> +                catch (OperationCanceledException)
Тут ты ловишь эксепшен отмены, а вот выше на 38 строке неть
почему?

2022-09-02 18:58 UTC, Orygeunik commented on Models/Validation.cs
> +            if (countPos == 0)
а что насчет
`return countPos == 0 || countPos > 0 && countPos < _settings.Pos.MaximumAmount;`

2022-09-02 18:58 UTC, Orygeunik commented on ViewModels/Result/PaperResult.cs
>          public int Sheets { get; set; } //листов необхзодимо
Если будешь использовать тройной коммент перед членом - у тебя будет везде подсказка, что это такое

2022-09-02 19:00 UTC, Orygeunik commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
>              catch
Так и?
Почему бы тогда не выпилить везде катчи, а просто в конце проверить сумму на больше нуля или нет

2022-09-02 21:33 UTC, HarryTheHatchet requested changes
Оставил пару замечаний и вопросов.

2022-09-02 21:33 UTC, MrGreedyCat commented on .gitignore
> +internal-nlog-AspNetCore.txt
Логи лучше складывать с отдельную папку (например logs) и исключать её, а не отдельные файлы.

2022-09-02 21:33 UTC, MrGreedyCat commented on ApplicationContext.cs
>          public DbSet<PricePaper> PricePapers { get; set; } = null!;
Не единый стиль именования. PricePaper и PaperCatalog, LaminationPrice и PricePaper. Лучше привести к единому стилю.

2022-09-02 21:33 UTC, MrGreedyCat commented on ApplicationContext.cs
>          public DbSet<History> Historys { get; set; } = null!;
History как Standalone слово - плохо. Это история чего? Стоит её назвать SomethingHistory и вместо Something указать история чего это. Так же множественное будет Histories...

2022-09-02 21:33 UTC, MrGreedyCat commented on ApplicationContext.cs
>          public DbSet<HistoryInput> HistoryInputs { get; set; } = null!;
Тут тоже стоило бы сделать реверт, InputHistory и plural соответственно.

2022-09-02 21:33 UTC, MrGreedyCat commented on Constants.cs
> +        public const string ReturnEmptyOutputHttp = "none";
А это простите зачем? Не понял смысла, с виду выглядит как костыль. Можно пояснение какая логика за этим спрятана?

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/ConsumablePrice.cs
> +        public int DrumPrice1 { get; set; }
Именование элементов с нумерацией - очень неочевидно.
Обычно это делается в виде IEnumerable<int> DrumPrice.
Если они имеют какой-то отдельный смысл и логику - дай им понятные названия чтоб не гадать что это такое.

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/History.cs
> +        public HistoryInput Input { get; set; } = null!;
Вот так лучше не делать.
Представим ситуацию. Ты сделал так, потом в каком-то методе ты обращаешься к этой проперте и студия (VS) в видит что объект not null и не показывает тебе уведомление. Но ты по факту форсишь туда null и во время выполнения получишь NRE, что крит.
Если же бурать присваивание null-а, то и добавить типу объекта nullable (?), то студия при попытке обратиться в коде к проперте скажет тебе что там может быть null и хорошо бы это проверить и реализовать логику на такой случай. Это заставит тебя (надеюсь) написать соответсвующий код и ты уже не получишь там ошибку на ровном месте.

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/History.cs
>          public LaminationPrice? LaminationPrices { get; set; }
А вот тут сделано через ?
Почему неконсистентно? Была какая-то веская причина использовать оба подхода?

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/HistoryInput.cs
>          public int Id { get; set; }
А почему у тебя в папке Database лежат модельки?
Если уж на то пошло, то создай в Database директории Models для моделек и Context для контекстов.
И это не Database, а DAL (Data Access Layer).

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/Lamination.cs
> +        public List<LaminationPrice> Price { get; set; } = null!;
Почему List? Почему не array или не IEnumerable?
Это не призыв поменять, просто интересно.

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/LaminationPrice.cs
>          public Lamination? Lamination { get; set; }
Кстати, а где все навигационные свойства и прочие атрибуты моделей DAL-а?

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/PaperCatalog.cs
> +        public List<PricePaper> Prices { get; set; } = new();
У тебя по сути PricePaper и LaminationPrice одинаковые кроме навигационной проперти, может объединить?

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/SizePaper.cs
> +        public string NameSizePaper { get; set; } = null!;
Свойство NameSizePaper в классе SizePaper? А почему тогда не IdSizePaper?
Советую из названия свойств убрать названия класса, дублирование ненужное.

2022-09-02 21:33 UTC, MrGreedyCat commented on DataBase/SizePaper.cs
>          public int SizePaperHeight { get; set; } //длинная чать
Коменты как правило пишутся сверху.
Ставишь над свйоством (или именем метода /// и студия генерит автоматически штку), эти коменты при работе с этими свойствами будут вылезать как подсказки в студии.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/CalculatingMarkup.cs
> +﻿using printing_calculator.Models.Settings;
Почему? Почему в папке моделей лежит что-то, что к моделям не имеет никакого отношения?
/смотрит осуждающе/

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/CalculatingMarkup.cs
А почему тут отступ между приватными полями?
Если уж отделять, то обычные поля от readonly полей...

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/CalculatingMarkup.cs
>          private readonly List<MarkupList> _markup;
List<MarkupList>?
У тебя класс MarkupList представляет из себя единственный item. Почему он в названии имеет list?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/CalculatingMarkup.cs
>              _markup = list;
А почему название list? Почему не a? Или b?
Не информативно.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/CalculatingMarkup.cs
> +            float factor = (float)1 - ((float)(sheets - _sheets) / (float)_difference);
Так, пятница, вечер, всё такое, не лучший час для ревью, однако!
_difference не инициализирован при создании. Значение по умолчанию для int - это 0.
Если в следующем методе (да, том что носит неинформативное название) не сработает условие на 35 строке, то difference заполнен не будет и останется нулём.
Знаешь что будет при делении на 0? Ничего хорошего.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/CalculatingMarkup.cs
> +        private void MaxMin(int shets)
А почему такое "информативное" название?
Ты через полгода вспомнишь что это за штука по названию?
Если не можешь в названии передать суть, то используй комент к методу (через ///).

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
> +                result.Price = Convert.ToInt32(Math.Round((double)result.Price / 10, 1) * 10); //округление
Что за магия?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
>                      result.PaperResult.ActualCostPrise &&
Учитывая что все эти действия проделываются над одной моделькой - можно в ней спрятать это всё и в метод например "bool IsActualPaperPrice()" и тут кода подсократится в тонны раз.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
> +                if (result.Price != history.Price)
Вообще этот метод ну ооооооочень странный. Я не смог по быстрому въехать в то что тут делается, но на первый взгляд либо что-то лишнее, либо оно не в той последовательности делается, либо что-то ещё.
Призываю Оружейника.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefaultAsync(cancellationToken);
Тут можно сделать SingleAsync и убрать последующую проверку на null и return внутри, результат будет тот же.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                int actualConsumableId = consumablePrice.Id;
Ты создаешь переменную чтоб её потом один раз использовать.
А почему нельзя не её, а consumablePrice.Id использовать? Зачем лишняя переменная?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                float CMUKprice = (float)history.ConsumablePrice.TonerPrice / (float)_consumable.CMYK;
А зачем везде так много приведений в float? Почему сразу в нём не хранить?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/IConveyor.cs
> +        public Task<(History, Result, bool)> TryConveyorStartAsync(History history, Result result, CancellationToken cancellationToken);
А почему интерфейс лежит вместе с обычными классами? Почему не в отдельной папке?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        private readonly Settings.Lamination _lamination1;
Что? Почему 1? Что-то "_lamination" уже занятой я не наблюдаю...

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            List<LaminationPrice> actualPriceId = lamination.Price;
Почему список называется Id?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            Lamination lamination = await _applicationContext.Laminations
Если тебе нужна только цена (причем последняя), то зачем тянуть весь объект ненужный?
Почему не выбрать только нужное?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            if (priceId == actualPriceId[^1].Id)
Все 4 строки можно записать так
return priceId == actualPriceId[^1].Id;

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationInfo.cs
> +                return Task.FromResult((history, result, true));
А зачем один и тот же код внутри условия и вне его?
Одного куска вне должно хватить.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
> +            int markup = (int)markups.GetMarkup(result.PaperResult.Sheets);
А зачем явный каст инта к инту?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
> +                return Task.FromResult((history, result, true));
Так же зачем return одного и того же в каждой ветке условия? Почему после условий нельзя вернуть его один раз?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
> +        private readonly Settings.Lamination _setting;
Почему у тебя во всех классах одно и то же называется по разному?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PaperCostPrice.cs
> +            {
return await _applicationContext.PaperCatalogs
                     .AsNoTracking()
                     .Where(paperCatalogs => paperCatalogs.Name == history.Input.Paper.Name)
                     .Select(x => x.Prices.Last().Id == history.PricePaper.Id)
                     .FirstAsync(cancellationToken);

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +                    return Task.FromResult((history, result, true));
Можно обойтись одним return-ом вне условий.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PaperMarkup.cs
> +            int markupPaper = (int)markup.GetMarkup(result.PaperResult.Sheets);
Снова ненужный каст.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PaperMarkup.cs
> +                return Task.FromResult((history, result, true));
Ну ты понял, да? )

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
> +                int? price = Convert.ToInt32(result.PaperResult.CostPrise + (result.PaperResult.CostPrise * (float)result.PaperResult.MarkupPaper / (float)100)) + result.PaperResult.CutPrics;
Эммм, у тебя 3 из 4-х параметров внутри - nullable. Работать с ними не проверив их на null - такое себе.
А после првоерки их на null можно и price сделать non nullable и убрать проверки и костыли вокруг этого.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PosDrilling.cs
> +            if (result.PosResult == null)
Эти две строки можно записать вот так
result.PosResult ??= new();

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PosDrilling.cs
> +            if (actualPrice == price)
Вот это всё можно упростить до
result.PosResult.ActualDrillingPrice = actualPrice == price;
return Task.FromResult((history, result, true));

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
> +            if (result.PosResult == null)
Аналогично соседнему файлу.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
> +            if (actualPrice == price)
Аналогично соседнему файлу.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculator.cs
> +            return await TryRun(history, result, AddConveyor(), cancellationToken);
Ты выделил целый метод чтоб вызвать другой метод? Эээээ?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/ConveyorCalculator.cs
>              result = new();
А зачем это тут? Почему не так же как с history поступить внутри условия?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/GeneratorHistory.cs
> +        private async Task<History> GetHistoryWithAsNoTracking(History history, Input input, CancellationToken cancellationToken)
А зачем добавлять WithAsNoTracking в название метода?
И почему бы не добавить Async  название метода?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/GeneratorHistory.cs
> +        public async Task<List<History>> GetListAsync(int page, int countPage, CancellationToken cancellationToken)
Метод с именем GetList должен делать return new List :)
Я бы название дал информативнее.

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/PaperSplitting.cs
Так, а какого этот файл вообще тут делает? Почему он не во внутренней папке где у тебя все конвейеры лежат?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Calculating/PaperSplitting.cs
>          private int PiecesPerSheet(SizePaper sizePaper, float SizeProdyctionHeight, float SizeProdyctionWidth)
Почему метод называется Prices (множественное число), а возвращает единственный жалкий int, а не скажем int[] или List<int>?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Converter.cs
> +            result.Lamination = history.Input.Lamination != null;
Почему часть свойств заполняется во время инициализации класса, а часть потом?

2022-09-02 21:33 UTC, MrGreedyCat commented on Models/Converter.cs
> +            return result;
return можно сделать сразу.

2022-09-02 21:33 UTC, HarryTheHatchet commented on Models/Validation.cs
> +        public async Task<bool> TryValidationInpytAsync(Input input, CancellationToken cancellationToken)
Простите, что валидировать?

2022-09-02 21:33 UTC, HarryTheHatchet commented on Models/Validation.cs
> +        private bool TryValidationSize(int? size)
Тогда уж TryValidate, а не TryValidation...

2022-09-02 21:33 UTC, HarryTheHatchet commented on Models/Validation.cs
> +            return size != null && size > 0 && size < _settings.SettingPrinter.MaximumSize;
Ты сюда передаешь дважды int без ?, зачем принимать nullable тип и делать проверку на null?

2022-09-02 21:33 UTC, HarryTheHatchet commented on Models/Validation.cs
> +                .AsNoTracking()
Вот тут я не уверен, но кажется Any не трекает изменения.

2022-09-02 21:33 UTC, HarryTheHatchet commented on Models/Validation.cs
> +        private static bool TryPositiveNumber(int number)
Не всё что возвращает bool должно начинаться с Try.
В данном случае это проверка является ли, так что тут применимо что-то вроде IsPositive.

И да, тебе реально проще вызвать метод чем просто на месте сделать сравнение?

2022-09-02 21:33 UTC, HarryTheHatchet commented on Models/Validation.cs
> +            return countPos > 0 && countPos < _settings.Pos.MaximumAmount; //не больше 50 биговок и дырок
Помимо && есть ещё и ||
Можно записать в одну строчку.

2022-09-02 21:33 UTC, HarryTheHatchet commented on Startup.cs
> +            services.Configure<Setting>(_configuration.GetSection("Settings"));
В строке можно опечататься. Лучше nameof(Settings)

2022-09-02 21:33 UTC, HarryTheHatchet commented on ViewModels/SimplResult.cs
> +    public class SimplResult
Simple

2022-09-02 21:33 UTC, HarryTheHatchet commented on Views/CalculatorResult/CalculatorResult.cshtml
> +@section JS
Ой, ну в cshtml класть и разметку и скрипты и стили - это прямо грязь.

2022-09-02 21:33 UTC, HarryTheHatchet commented on Views/CalculatorResult/CalculatorResult.cshtml
>  						<p class="margin">Листов:шт/лист</p>
Там выше был текст "чистая прибыль", не даёт туда поставить комент.
Так вот, ты туда заложил и амортизацию оборудрвания и аренду помещения и ЗП сотрудников и прочие неявные штуки?
Почему вдруг "чистая" прибыль?

2022-09-02 21:33 UTC, HarryTheHatchet commented on Views/CalculatorResult/CalculatorResult.cshtml
>  <div class="button">
Вообще всю форму лучше сделать в теге form и поля формировать через TagHelper-ы, тогда с бека можно будет через модельки подтягивать валидации и прочие штуки, а сабмит формы по кнопке станет проще.

2022-09-02 21:33 UTC, HarryTheHatchet commented on Views/Shared/PageOtvet.cshtml
>  <body>
Как файл называется? Otvet?
/нервно трёт глаза/

2022-09-02 21:33 UTC, HarryTheHatchet commented on Views/Shared/_Layout.cshtml
> -	@RenderSection("Stail",false)
Style

2022-09-02 21:33 UTC, HarryTheHatchet commented on Views/Shared/_Layout.cshtml
> +	@RenderSection("Style",false)
Стоп, что?

2022-09-02 21:33 UTC, HarryTheHatchet commented on appsetting.PRODUCTION.json
> +        "DefaultConnection": "Host=localhost;Port=5432;Database=Calculator;Username=asp;Password=159"
/удар линейкой по рукам/

2022-09-02 21:33 UTC, HarryTheHatchet commented on appsettings.json
> +            "Adjustment": 50, //цена приладки ламинации
Коменты в json... Низя

2022-09-02 21:33 UTC, HarryTheHatchet commented on controllers/CalculatorController.cs
> +        public CalculatorController(ApplicationContext applicationContext, ILogger<CalculatorController> logger)
Context-ы лучше не дёргать напрямую в классах и тем более контроллерах, а прятать их за Provider или Repository (кому как нравится).

2022-09-02 21:33 UTC, HarryTheHatchet commented on controllers/CalculatorResultController.cs
> +                    await _applicationContext.SaveChangesAsync(cancellationToken);
А уверен ли ты что туда надо токен отмены передавать? Обычно сохранить в базу стараются при любой ситуации.

2022-09-02 21:33 UTC, HarryTheHatchet commented on controllers/CalculatorResultController.cs
> +                ConveyorCalculator conveyor = _calculator;
А вот это действие зачем?

2022-09-02 21:33 UTC, HarryTheHatchet commented on controllers/HistoryController.cs
Там чуть выше странный код, можно сильно упростить. А учитывая что он вызывается в одном месте - метод вообще выпилить нафиг.

2022-09-02 21:33 UTC, HarryTheHatchet commented on nlog.config
> +      internalLogFile="log/internal-nlog-AspNetCore.txt">
О. я как раз про это писал где-то в начале, не забудь папку log добавить в gitignore.
Либо пиши логи в файлы с расширением .log и добавить исключение этого расширения.

2022-09-02 21:40 UTC, Orygeunik commented on controllers/CalculatorController.cs
> +        public CalculatorController(ApplicationContext applicationContext, ILogger<CalculatorController> logger)
Repository - порочная практика, от нее все отказываются уже

2022-09-02 21:40 UTC, Orygeunik commented on controllers/CalculatorResultController.cs
> +                    await _applicationContext.SaveChangesAsync(cancellationToken);
Это правильный подход
Нет смысла сохранять в базу, если юзер у себя на стороне браузера нажал кнопку escape

2022-09-05 07:24 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PosRounding.cs
>              int? Price = history.RoundingPrice;
Проверил, варнинги поправил.

2022-09-05 07:25 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            if (priceId == actualPriceId[^1].Id)
Схлопнул

2022-09-05 07:26 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        private readonly Settings.Lamination _lamination1;
Видимо когда разыменовывал случайно проскочило. Поправил

2022-09-05 07:30 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
>              catch
А оно точно минусом будет? А если предположить что оно на столько уйдет на второй круг что дойдет до плюсовых значений? Разве такое не может быть? Не лучше уж ошибку ловить просто?

2022-09-05 07:36 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperPriсe.cs
> +                int? price = Convert.ToInt32(result.PaperResult.CostPrise + (result.PaperResult.CostPrise * (float)result.PaperResult.MarkupPaper / (float)100)) + result.PaperResult.CutPrics;
Разделил на 2 выражения.

2022-09-05 13:44 UTC, oJieg commented on Models/Calculating/GeneratorHistory.cs
> +                    .AsNoTracking()
материализация - звучит круто) Исправил.

2022-09-05 14:47 UTC, oJieg commented on Models/Validation.cs
> +                catch (OperationCanceledException)
забыл, поправил.

2022-09-05 14:54 UTC, oJieg commented on Models/Validation.cs
> +            if (countPos == 0)
ну дааа, так лучше

2022-09-05 14:54 UTC, oJieg commented on ViewModels/Result/PaperResult.cs
>          public int Sheets { get; set; } //листов необхзодимо
Точно, каждый раз забываю про эту фишку.

2022-09-05 14:59 UTC, oJieg commented on .gitignore
> +internal-nlog-AspNetCore.txt
Так оно у меня и есть. Забыл просто из игнора исключить.

2022-09-06 07:29 UTC, oJieg commented on Constants.cs
> +        public const string ReturnEmptyOutputHttp = "none";
У меня в двух разных классах используется строка "none", Василий сказал - лучше вынеси как константу ее отдельно. Ну вот я и вынес ее отдельно.

2022-09-06 07:36 UTC, oJieg commented on DataBase/ConsumablePrice.cs
> +        public int DrumPrice1 { get; set; }
Это фотобарабаны в цифровой машине. Их 4 штуки, при этом цена у них не одинаковая. В машине они так и нумеруются. Не вижу особого смысла делать их IEnumerable

2022-09-06 07:43 UTC, oJieg commented on DataBase/Lamination.cs
> +        public List<LaminationPrice> Price { get; set; } = null!;
Да просто так в последствии проще добавлять новые элементы. Теоретически туда достаточно части придется добавлять новые элементы.

2022-09-06 07:45 UTC, oJieg commented on DataBase/LaminationPrice.cs
>          public Lamination? Lamination { get; set; }
Вроде же они автоматически генерируются, а лично мне доступ, к этим навигационным свойствам, особо не нужен

2022-09-06 07:54 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
Какая то внутренняя логика у меня была на этот счет. Сейчас уже сам не понимаю зачем так сделал. Убрал.

2022-09-06 09:09 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
>          private readonly List<MarkupList> _markup;
Ну как же один? Вот в json их целый список. По этому так и назвал. Я реально не знаю как иначе назвать этот класс 
![image](https://user-images.githubusercontent.com/16959001/188595652-f891a737-5f1c-4cb9-9dcf-8adf078064bd.png)

2022-09-06 13:31 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
>          private readonly List<MarkupList> _markup;
Переименовал в markups

2022-09-06 15:02 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
>              _markup = list;
Поправил.

2022-09-06 15:36 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
> +            float factor = (float)1 - ((float)(sheets - _sheets) / (float)_difference);
Запихнул проверку, названия поменял. Надеюсь более понятные стали)

2022-09-06 15:39 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
> +        private void MaxMin(int shets)
Ок, поправил и название и комментарий добавил.

2022-09-06 15:43 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
> +                result.Price = Convert.ToInt32(Math.Round((double)result.Price / 10, 1) * 10); //округление
нолик похерился) Но вообще это округление до десяток. Поправил.

2022-09-07 19:31 UTC, HarryTheHatchet commented on Constants.cs
> +        public const string ReturnEmptyOutputHttp = "none";
Тут вопрос скорее в том, а почему у тебя извне приходит none? Почему не string.Empty и проверять на неё, зачем константа-заглушка под нечто ненужное?
Или почему не сделать его nullable и не проверять на null?

2022-09-07 19:33 UTC, HarryTheHatchet commented on DataBase/ConsumablePrice.cs
> +        public int DrumPrice1 { get; set; }
А в машине они так и называются, "1, 2 и так далее"? Может у них есть более нормальные названия?

2022-09-07 19:33 UTC, HarryTheHatchet commented on DataBase/Lamination.cs
> +        public List<LaminationPrice> Price { get; set; } = null!;
А почему List.Add проще чем IEnumerable.Append? Из-за кол-ва буков, да? )

2022-09-07 19:43 UTC, HarryTheHatchet commented on Models/Calculating/CalculatingMarkup.cs
>          private readonly List<MarkupList> _markup;
Да, всё неплохо, но не совсем.
Я бы предложил назвать класс Markup - в единственном числе, а вот List<Markup> можно уже назвать _markups.

2022-09-12 12:58 UTC, oJieg commented on Constants.cs
> +        public const string ReturnEmptyOutputHttp = "none";
Аа, ну да так можно сделать) 
Исправил.

2022-09-12 13:02 UTC, oJieg commented on DataBase/ConsumablePrice.cs
> +        public int DrumPrice1 { get; set; }
Да они так и называются, в том и прикол) А из за относительно долгого срока службы, есть очень даже вариант установки одновременно более дешевых(давно купленных)  и более дорогих(недавно купленных) барабанов.

2022-09-12 14:00 UTC, oJieg commented on DataBase/Lamination.cs
> +        public List<LaminationPrice> Price { get; set; } = null!;
Ну например в list можно удалять и добавлять по индексу. IEnumerable.Append, как я понимаю пересоздает объект плюс ко всему. Ну и самое главное не люблю я IEnumerable)

2022-09-12 14:15 UTC, oJieg commented on Models/Calculating/CalculatingMarkup.cs
>          private readonly List<MarkupList> _markup;
Ладно, так и сделал, только переименовал переменную Markup в MarkupForThisPage. Теперь Json выглядит еще чуть более понятно. 
![image](https://user-images.githubusercontent.com/16959001/189676874-89fc0981-d347-4482-9c4c-e0ffb2231bf3.png)

2022-09-12 14:30 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
>                      result.PaperResult.ActualCostPrise &&
Хорошо, убрал.

2022-09-12 14:34 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/AllPrice.cs
> +                if (result.Price != history.Price)
А что странного? Сначала происходит округление, после если в базе нет информации о цене то добавит, а если есть уже то сверит с получившийся ценой, но в любом случаи выведет цену которая в базе сохранена, единственное с пометкой о том что цена не актуальная и требуется все пересчитать. У меня такая логика в в других этапах конвейера.

2022-09-12 14:42 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                    .FirstOrDefaultAsync(cancellationToken);
Не очень понял как это поможет избавится от проверки на null? все равно же это не исключит того случая если нет не одного элемента в базе. Оно конечно через исключение пойдет просто, но на прямую не лучше разве такое проверять?

2022-09-12 14:43 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                int actualConsumableId = consumablePrice.Id;
Ага, лишняя, убрал.

2022-09-12 14:53 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/ConsumablePrice.cs
> +                float CMUKprice = (float)history.ConsumablePrice.TonerPrice / (float)_consumable.CMYK;
Да точность такая не требуется. Точность float  нужна дальше только.

2022-09-12 14:54 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +        private readonly Settings.Lamination _lamination1;
Поправил, видимо разыменовывал когда то(

2022-09-12 15:00 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            List<LaminationPrice> actualPriceId = lamination.Price;
У меня была логика следующая - мне в данном случаи нужен от LaminationPrice только id, остальная информация побочная просто, по этому и такое название) 
Плохая логика? Сделать все же просто actualPrice?

2022-09-12 15:07 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            Lamination lamination = await _applicationContext.Laminations
Не совсем понимаю - если я возьму сразу price и отсортирую по принадлежности к нужным объектам Lamination, то я все равно не смогу получить последовательность добавления цен. Теоретически только List в Lamination хранит верную последовательность изменения цен.

2022-09-12 15:08 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            if (priceId == actualPriceId[^1].Id)
Да это я поправил, чет реально тупняк какой то)

2022-09-12 15:09 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationInfo.cs
> +                return Task.FromResult((history, result, true));
логично, убрал.

2022-09-12 15:11 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
> +            int markup = (int)markups.GetMarkup(result.PaperResult.Sheets);
хм, догадываюсь что раньше у меня .GetMarkup возвращал int?, а потом я это поправил, а тут конечно не поправил.

2022-09-12 15:11 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
> +            int markup = (int)markups.GetMarkup(result.PaperResult.Sheets);
Исправил

2022-09-12 15:12 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationMarkup.cs
> +                return Task.FromResult((history, result, true));
Исправил.

2022-09-12 15:21 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationPriсe.cs
> +        private readonly Settings.Lamination _setting;
Ну логика тут такая же странная, в предыдущем классе мне нужен был только markup, по этому так и назвал. 
Но я поменял все равно именование тут и там)

2022-09-12 16:09 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCostPrice.cs
> +            {
хм, Select - прикольная штука, не знал.

2022-09-12 16:09 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/LamonationCostPriсe.cs
> +            Lamination lamination = await _applicationContext.Laminations
просто я про Select не знал)

2022-09-13 07:14 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperCutPriсe.cs
> +                    return Task.FromResult((history, result, true));
Сделал

2022-09-13 07:14 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperMarkup.cs
> +            int markupPaper = (int)markup.GetMarkup(result.PaperResult.Sheets);
Убрал

2022-09-13 07:15 UTC, oJieg commented on Models/Calculating/ConveyorCalculating/PaperMarkup.cs
> +                return Task.FromResult((history, result, true));
Понял)

2022-09-28 09:50 UTC, Orygeunik approved these changes

2022-09-28 09:51 UTC, merged